/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aula01.swing;

import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411033
 */

    
public class NewJFrameAula01 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameAula01
     */
    public NewJFrameAula01() {
        initComponents();
    }
    
    double valor1, valor2;
    String operacao;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btnNumeroDois = new javax.swing.JButton();
        btnNumeroUm = new javax.swing.JButton();
        btnNumeroQuatro = new javax.swing.JButton();
        btnNumeroTres = new javax.swing.JButton();
        btnNumeroSete = new javax.swing.JButton();
        btnNumeroSeis = new javax.swing.JButton();
        btnNumeroCinco = new javax.swing.JButton();
        btnNumeroOito = new javax.swing.JButton();
        btnNumeroNove = new javax.swing.JButton();
        btnNumeroDoisZero = new javax.swing.JButton();
        btnNumeroMenos = new javax.swing.JButton();
        btnNumeroMais = new javax.swing.JButton();
        btnNumeroMultiplicacao = new javax.swing.JButton();
        btnNumeroDivisao = new javax.swing.JButton();
        lblHistorico = new javax.swing.JLabel();
        btnCE = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCC = new javax.swing.JButton();
        btnPorce = new javax.swing.JButton();
        btnNumeroZeroTres = new javax.swing.JButton();
        btnNumeroZero = new javax.swing.JButton();
        btnCE1 = new javax.swing.JButton();
        btnExponencial = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIgual.setBackground(new java.awt.Color(51, 102, 255));
        btnIgual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("CALCULADORA M1200");

        txtResultado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        btnNumeroDois.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroDois.setText("2");
        btnNumeroDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroDoisActionPerformed(evt);
            }
        });

        btnNumeroUm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroUm.setText("1");
        btnNumeroUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroUmActionPerformed(evt);
            }
        });

        btnNumeroQuatro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroQuatro.setText("4");
        btnNumeroQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroQuatroActionPerformed(evt);
            }
        });

        btnNumeroTres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroTres.setText("3");
        btnNumeroTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroTresActionPerformed(evt);
            }
        });

        btnNumeroSete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroSete.setText("7");
        btnNumeroSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroSeteActionPerformed(evt);
            }
        });

        btnNumeroSeis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroSeis.setText("6");
        btnNumeroSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroSeisActionPerformed(evt);
            }
        });

        btnNumeroCinco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroCinco.setText("5");
        btnNumeroCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroCincoActionPerformed(evt);
            }
        });

        btnNumeroOito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroOito.setText("8");
        btnNumeroOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroOitoActionPerformed(evt);
            }
        });

        btnNumeroNove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroNove.setText("9");
        btnNumeroNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroNoveActionPerformed(evt);
            }
        });

        btnNumeroDoisZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroDoisZero.setText("00");
        btnNumeroDoisZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroDoisZeroActionPerformed(evt);
            }
        });

        btnNumeroMenos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNumeroMenos.setText("-");
        btnNumeroMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroMenosActionPerformed(evt);
            }
        });

        btnNumeroMais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNumeroMais.setText("+");
        btnNumeroMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroMaisActionPerformed(evt);
            }
        });

        btnNumeroMultiplicacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNumeroMultiplicacao.setText("*");
        btnNumeroMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroMultiplicacaoActionPerformed(evt);
            }
        });

        btnNumeroDivisao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNumeroDivisao.setText("/");
        btnNumeroDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroDivisaoActionPerformed(evt);
            }
        });

        lblHistorico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHistorico.setForeground(new java.awt.Color(153, 153, 153));
        lblHistorico.setText(" ");

        btnCE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCC.setText("CC");
        btnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCActionPerformed(evt);
            }
        });

        btnPorce.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPorce.setText("%");
        btnPorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorceActionPerformed(evt);
            }
        });

        btnNumeroZeroTres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroZeroTres.setText("000");
        btnNumeroZeroTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroZeroTresActionPerformed(evt);
            }
        });

        btnNumeroZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNumeroZero.setText("0");
        btnNumeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroZeroActionPerformed(evt);
            }
        });

        btnCE1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCE1.setText(",");
        btnCE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCE1ActionPerformed(evt);
            }
        });

        btnExponencial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExponencial.setText("X²");
        btnExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExponencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtResultado)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblHistorico)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumeroUm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumeroDois)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumeroTres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumeroQuatro))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNumeroCinco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCE1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnNumeroSeis))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNumeroDoisZero)
                                            .addComponent(btnNumeroNove))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNumeroSete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNumeroZeroTres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnNumeroZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelete)
                                    .addComponent(btnNumeroOito)
                                    .addComponent(btnCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumeroMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNumeroDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNumeroMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPorce, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExponencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNumeroMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(33, 33, 33))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIgual, btnNumeroDivisao, btnNumeroMais, btnNumeroMenos, btnNumeroMultiplicacao, btnPorce});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCC, btnCE, btnDelete, btnNumeroCinco, btnNumeroDois, btnNumeroDoisZero, btnNumeroNove, btnNumeroOito, btnNumeroQuatro, btnNumeroSeis, btnNumeroSete, btnNumeroTres, btnNumeroUm});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(lblHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroMais, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPorce, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroDois, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroUm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroTres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroOito, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroSete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNumeroNove, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroZero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroDoisZero, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNumeroZeroTres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCE1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnIgual, btnNumeroDivisao, btnNumeroMais, btnNumeroMenos, btnNumeroMultiplicacao, btnPorce});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCC, btnCE, btnDelete, btnNumeroCinco, btnNumeroDois, btnNumeroDoisZero, btnNumeroNove, btnNumeroOito, btnNumeroQuatro, btnNumeroSeis, btnNumeroSete, btnNumeroTres, btnNumeroUm});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumeroDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroDoisActionPerformed
       txtResultado.setText(txtResultado.getText() + "2");
    }//GEN-LAST:event_btnNumeroDoisActionPerformed

    private void btnNumeroQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroQuatroActionPerformed
       txtResultado.setText(txtResultado.getText() + "4");
    }//GEN-LAST:event_btnNumeroQuatroActionPerformed

    private void btnNumeroSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroSeisActionPerformed
        txtResultado.setText(txtResultado.getText() + "6");
    }//GEN-LAST:event_btnNumeroSeisActionPerformed

    private void btnNumeroOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroOitoActionPerformed
        txtResultado.setText(txtResultado.getText() + "8");
    }//GEN-LAST:event_btnNumeroOitoActionPerformed

    private void btnNumeroDoisZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroDoisZeroActionPerformed
        txtResultado.setText(txtResultado.getText() + "00");
    }//GEN-LAST:event_btnNumeroDoisZeroActionPerformed

    private void btnNumeroMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroMenosActionPerformed

        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "-";      
    }//GEN-LAST:event_btnNumeroMenosActionPerformed

    private void btnNumeroMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroMaisActionPerformed
        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "+";
    }//GEN-LAST:event_btnNumeroMaisActionPerformed

    private void btnNumeroMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroMultiplicacaoActionPerformed
        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "*";
    }//GEN-LAST:event_btnNumeroMultiplicacaoActionPerformed

    private void btnNumeroDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroDivisaoActionPerformed
        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "/";
    }//GEN-LAST:event_btnNumeroDivisaoActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnNumeroUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroUmActionPerformed
        txtResultado.setText(txtResultado.getText() + "1");
    }//GEN-LAST:event_btnNumeroUmActionPerformed

    private void btnNumeroSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroSeteActionPerformed
        txtResultado.setText(txtResultado.getText() + "7");
    }//GEN-LAST:event_btnNumeroSeteActionPerformed

    private void btnNumeroNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroNoveActionPerformed
        txtResultado.setText(txtResultado.getText() + "9");
    }//GEN-LAST:event_btnNumeroNoveActionPerformed

    private void btnNumeroCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroCincoActionPerformed
        txtResultado.setText(txtResultado.getText() + "5");
    }//GEN-LAST:event_btnNumeroCincoActionPerformed

    private void btnNumeroTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroTresActionPerformed
        txtResultado.setText(txtResultado.getText() + "3");
    }//GEN-LAST:event_btnNumeroTresActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
      
        double resultado;
        
        valor2 = Double.parseDouble(txtResultado.getText());
        
        if(operacao == "+")
        {
            resultado = valor1 + valor2;
            lblHistorico.setText(valor1+"+"+valor2+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));
        }
        else if(operacao == "-")
        {
            resultado = valor1 - valor2;
            lblHistorico.setText(valor1+"-"+valor2+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));            
        }
        else if(operacao == "*")
        {
            resultado = valor1 * valor2;
            lblHistorico.setText(valor1+"*"+valor2+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));            
        }        
        else if(operacao == "/")
        {
            resultado = valor1 / valor2;
            lblHistorico.setText(valor1+"/"+valor2+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));            
        }
        else if(operacao == "%")
        {
            resultado = (valor1 / 100) * valor2;
            lblHistorico.setText(valor1+"%"+valor2+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));               
        }
        else if(operacao == "^")
        {
            resultado =  valor1 * valor1 ;
            lblHistorico.setText(valor1+"^ 2"+"=");
            //txtResultado.setText(Double.toString(resultado));
            txtResultado.setText(String.valueOf(resultado));               
        }
        else
        {
           
            lblHistorico.setText("Invalid Operation!!!");
            
        }
                    
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        txtResultado.setText("");
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String textoAtual = txtResultado.getText();
        String novaExpressao;
        
        novaExpressao = textoAtual.substring(0, textoAtual.length() - 1);
        
        txtResultado.setText(novaExpressao);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorceActionPerformed
        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "%";        
    }//GEN-LAST:event_btnPorceActionPerformed

    private void btnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCActionPerformed
         txtResultado.setText("");
         lblHistorico.setText("");
    }//GEN-LAST:event_btnCCActionPerformed

    private void btnNumeroZeroTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroZeroTresActionPerformed
        txtResultado.setText(txtResultado.getText() + "000");

    }//GEN-LAST:event_btnNumeroZeroTresActionPerformed

    private void btnNumeroZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroZeroActionPerformed
        txtResultado.setText(txtResultado.getText() + "0");
    }//GEN-LAST:event_btnNumeroZeroActionPerformed

    private void btnCE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCE1ActionPerformed
        txtResultado.setText(txtResultado.getText() + ".");
    }//GEN-LAST:event_btnCE1ActionPerformed

    private void btnExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExponencialActionPerformed
        lblHistorico.setText(txtResultado.getText());
        txtResultado.setText("");
        
        valor1 = Double.parseDouble(lblHistorico.getText());
        operacao = "^";
        txtResultado.setText("2");
    }//GEN-LAST:event_btnExponencialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAula01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAula01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAula01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAula01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameAula01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCE1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExponencial;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnNumeroCinco;
    private javax.swing.JButton btnNumeroDivisao;
    private javax.swing.JButton btnNumeroDois;
    private javax.swing.JButton btnNumeroDoisZero;
    private javax.swing.JButton btnNumeroMais;
    private javax.swing.JButton btnNumeroMenos;
    private javax.swing.JButton btnNumeroMultiplicacao;
    private javax.swing.JButton btnNumeroNove;
    private javax.swing.JButton btnNumeroOito;
    private javax.swing.JButton btnNumeroQuatro;
    private javax.swing.JButton btnNumeroSeis;
    private javax.swing.JButton btnNumeroSete;
    private javax.swing.JButton btnNumeroTres;
    private javax.swing.JButton btnNumeroUm;
    private javax.swing.JButton btnNumeroZero;
    private javax.swing.JButton btnNumeroZeroTres;
    private javax.swing.JButton btnPorce;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHistorico;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
