/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastroalunos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 2830482411033
 */
public class frmCadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form frmCadastroAlunos
     */
    public frmCadastroAlunos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg_Cursos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Alunos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        rbtn_Ds = new javax.swing.JRadioButton();
        rbtn_Gc = new javax.swing.JRadioButton();
        rbtn_Si = new javax.swing.JRadioButton();
        rbtn_Cd = new javax.swing.JRadioButton();
        btn_RemoverSelecionado = new javax.swing.JButton();
        btn_AlterarSelecionado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel3.setText("Idade");

        jLabel4.setText("Curso");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tbl_Alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Idade", "Curso"
            }
        ));
        jScrollPane1.setViewportView(tbl_Alunos);

        jLabel5.setText("Lista de Alunos");

        btg_Cursos.add(rbtn_Ds);
        rbtn_Ds.setText("Desenvolvimento de Sistemas");

        btg_Cursos.add(rbtn_Gc);
        rbtn_Gc.setText("Gestão Comercial");

        btg_Cursos.add(rbtn_Si);
        rbtn_Si.setText("Sistemas de Informação");

        btg_Cursos.add(rbtn_Cd);
        rbtn_Cd.setText("Ciência de Dados");

        btn_RemoverSelecionado.setBackground(new java.awt.Color(255, 51, 51));
        btn_RemoverSelecionado.setText("Remover Selecionado");
        btn_RemoverSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoverSelecionadoActionPerformed(evt);
            }
        });

        btn_AlterarSelecionado.setBackground(new java.awt.Color(51, 153, 255));
        btn_AlterarSelecionado.setText("Alterar Selecionado");
        btn_AlterarSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(400, 400, 400)
                                        .addComponent(btnAdicionar))
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_AlterarSelecionado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_RemoverSelecionado)))
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_Ds)
                                    .addComponent(rbtn_Si))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtn_Gc)
                                    .addComponent(rbtn_Cd))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(217, 217, 217))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_Ds)
                            .addComponent(rbtn_Gc))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn_Si)
                    .addComponent(rbtn_Cd))
                .addGap(53, 53, 53)
                .addComponent(btnAdicionar)
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_RemoverSelecionado)
                    .addComponent(btn_AlterarSelecionado))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        
        
        String curso = "";
        
        if(rbtn_Ds.isSelected()){
            curso = "Análise e Desenvolvimento de Sistemas";
        }
        else if(rbtn_Cd.isSelected()){
            curso = "Ciência de Dados";
        }
        else if(rbtn_Gc.isSelected()){
            curso = "Gestão Comercial";
        }
        else if(rbtn_Si.isSelected()){
            curso = "Sistemas de Informação";
        }
        // Cria o objeto
        Aluno a = new Aluno(txtNome.getText(), Integer.parseInt(txtIdade.getText()), curso);
        
        
        // Adiciona na tabela
         DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
         tabela.addRow(a.obterDados());
         
         txtNome.setText("");
         txtIdade.setText("");
         btg_Cursos.clearSelection();

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btn_RemoverSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoverSelecionadoActionPerformed

        DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
        int linhaselecionada = tbl_Alunos.getSelectedRow(); // pega a linha selecionada
        
        if(linhaselecionada == -1){
            JOptionPane.showMessageDialog(null, "Por Favor, selecione um registro para apagar");
        }
        else
        {
            // remove da tabela
            tabela.removeRow(linhaselecionada);
        }
    }//GEN-LAST:event_btn_RemoverSelecionadoActionPerformed

    private void btn_AlterarSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarSelecionadoActionPerformed

        String nome;
        String idade;
        String curso;

        DefaultTableModel tabela = (DefaultTableModel) tbl_Alunos.getModel();
        // 1 - pego o item selecionado e preencho os campos com os dados dele
        int linhaselecionada = tbl_Alunos.getSelectedRow(); // pega a linha selecionada

        if(linhaselecionada == -1){
            JOptionPane.showMessageDialog(null, "Por Favor, selecione um registro para alterar");
        }
        else
        {
            // pegar os valores das linhas selecionadas
            nome = tabela.getValueAt(linhaselecionada, 0).toString(); // linha para pegar o valor na linha selecionada, na coluna de nome
            idade = tabela.getValueAt(linhaselecionada, 1).toString(); // linha para pegar o valor na linha selecionada, na coluna de idade
            curso = tabela.getValueAt(linhaselecionada, 2).toString(); // linha para pegar o valor na linha selecionada, na coluna de curso
            
            
                    
            tabela.setValueAt(txtNome.getText(),linhaselecionada, 0);
            tabela.setValueAt(txtIdade.getText(), linhaselecionada, 1);

        }

    }//GEN-LAST:event_btn_AlterarSelecionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btg_Cursos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btn_AlterarSelecionado;
    private javax.swing.JButton btn_RemoverSelecionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtn_Cd;
    private javax.swing.JRadioButton rbtn_Ds;
    private javax.swing.JRadioButton rbtn_Gc;
    private javax.swing.JRadioButton rbtn_Si;
    private javax.swing.JTable tbl_Alunos;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
