/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ItensNotaDAO;
import DAO.NotaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Nota;
import model.ProdutosNota;

/**
 *
 * @author akiamara
 */
public class ConsultarNotas extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarNotas
     */
    public ConsultarNotas() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNota = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItensNota1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnConsultarItens = new javax.swing.JButton();
        btnRecarregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblNota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Data Emissão", "Valor Total", "Pagamento", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tblNota);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Itens na nota");

        tblItensNota1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Valor", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(tblItensNota1);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setText("Notas Emitidas");

        btnConsultarItens.setBackground(new java.awt.Color(51, 204, 255));
        btnConsultarItens.setText("Consultar Itens da Nota Selecionada");
        btnConsultarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItensActionPerformed(evt);
            }
        });

        btnRecarregar.setBackground(new java.awt.Color(238, 213, 97));
        btnRecarregar.setText("Recarregar");
        btnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(383, 383, 383))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRecarregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarItens)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultarItens)
                    .addComponent(btnRecarregar))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItensActionPerformed
     
        ItensNotaDAO iDAO = new ItensNotaDAO();
        
        DefaultTableModel tabelaItens = (DefaultTableModel) tblItensNota1.getModel();
        DefaultTableModel tabelaNotas = (DefaultTableModel) tblNota.getModel();
        int linha = tblNota.getSelectedRow();
                
        tabelaItens.setRowCount(0); // esvazio a tabela antes de popula-la novamente
        
        List<ProdutosNota> listaItens=  iDAO.consultarProdutosNota(Integer.parseInt(tabelaNotas.getValueAt(linha, 0).toString()));
        

        for(ProdutosNota item : listaItens) {
            Object[] obj = new Object[]{
                item.getProduto().getProdutoCodigo(),
                item.getProduto().getProdutoNome(),
                item.getValorUnidade(),
                item.getQuantidade()
            };
            tabelaItens.addRow(obj);
               
        }                
    }//GEN-LAST:event_btnConsultarItensActionPerformed

    private void btnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecarregarActionPerformed
        DefaultTableModel tabelaNotas = (DefaultTableModel) tblNota.getModel();
        tabelaNotas.setRowCount(0); // uso isso para setar os campos para 0, eliminando TODAS as linhas

        // Preencho a tabela novamente
        preencherTabela();

    }//GEN-LAST:event_btnRecarregarActionPerformed

    
    public void preencherTabela() {
        
        NotaDAO nDAO = new NotaDAO();
        
        List<Nota> listaNotas = nDAO.consultarNotas();
        
        DefaultTableModel tabelaPessoas = (DefaultTableModel) tblNota.getModel();
               
        
        for(Nota nota : listaNotas) {
            Object[] obj = new Object[]{
                nota.getCodigo(),
                nota.getDataEmissao(),
                nota.getValorTotal(),
                nota.getFormaPagamento(),
                (nota.isTipoNota()? "Saida": "Entrada")
            };
            tabelaPessoas.addRow(obj);
               
        }       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarItens;
    private javax.swing.JButton btnRecarregar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItensNota1;
    private javax.swing.JTable tblNota;
    // End of variables declaration//GEN-END:variables
}
