/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author akiamara
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        txtImagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniCadCliente = new javax.swing.JMenuItem();
        mniCadFornecedor = new javax.swing.JMenuItem();
        mniCadNotas = new javax.swing.JMenuItem();
        mniCadProdutos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mniConsultarCliente = new javax.swing.JMenuItem();
        mniConsultarFornecedores = new javax.swing.JMenuItem();
        mniConsuProd = new javax.swing.JMenuItem();
        mniNotas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        txtImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 82, 82));
        jLabel1.setText("SCV ORFEU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("O SEU SISTEMA DE COMPRA E VENDA");

        jMenu1.setText("Cadastro");

        mniCadCliente.setText("Cadastro de Cliente");
        mniCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadCliente);

        mniCadFornecedor.setText("Cadastro de Fornecedor");
        mniCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadFornecedor);

        mniCadNotas.setText("Cadastro de Notas");
        mniCadNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadNotasActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadNotas);

        mniCadProdutos.setText("Cadastro de Produtos");
        mniCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCadProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(mniCadProdutos);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Relatórios");

        mniConsultarCliente.setText("Consultar Cliente");
        mniConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(mniConsultarCliente);

        mniConsultarFornecedores.setText("Consultar Fornecedor");
        mniConsultarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultarFornecedoresActionPerformed(evt);
            }
        });
        jMenu5.add(mniConsultarFornecedores);

        mniConsuProd.setText("Consultar Produtos");
        mniConsuProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsuProdActionPerformed(evt);
            }
        });
        jMenu5.add(mniConsuProd);

        mniNotas.setText("Consultar Notas Fiscais");
        mniNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNotasActionPerformed(evt);
            }
        });
        jMenu5.add(mniNotas);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadProdutosActionPerformed
        FormularioProduto frmProd = new FormularioProduto();
        frmProd.setVisible(true);
    }//GEN-LAST:event_mniCadProdutosActionPerformed

    private void mniCadNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadNotasActionPerformed
        FormularioNota frmNota = new FormularioNota();
        frmNota.setVisible(true);
    }//GEN-LAST:event_mniCadNotasActionPerformed

    private void mniCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadFornecedorActionPerformed
        FormularioFornecedor frmForn = new FormularioFornecedor();
        frmForn.setVisible(true);
    }//GEN-LAST:event_mniCadFornecedorActionPerformed

    private void mniCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCadClienteActionPerformed
        FormularioCliente frmCli = new FormularioCliente();
        frmCli.setVisible(true);
    }//GEN-LAST:event_mniCadClienteActionPerformed

    private void mniConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultarClienteActionPerformed
        ConsultarCliente csC = new ConsultarCliente();
        csC.setVisible(true);
    }//GEN-LAST:event_mniConsultarClienteActionPerformed

    private void mniConsuProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsuProdActionPerformed
        ConsultarProduto csP = new ConsultarProduto();
        csP.setVisible(true);
    }//GEN-LAST:event_mniConsuProdActionPerformed

    private void mniConsultarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultarFornecedoresActionPerformed
        ConsultarFornecedor csF = new ConsultarFornecedor();
        csF.setVisible(true);
    }//GEN-LAST:event_mniConsultarFornecedoresActionPerformed

    private void mniNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNotasActionPerformed
        ConsultarNotas csN = new ConsultarNotas();
        csN.setVisible(true);
    }//GEN-LAST:event_mniNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mniCadCliente;
    private javax.swing.JMenuItem mniCadFornecedor;
    private javax.swing.JMenuItem mniCadNotas;
    private javax.swing.JMenuItem mniCadProdutos;
    private javax.swing.JMenuItem mniConsuProd;
    private javax.swing.JMenuItem mniConsultarCliente;
    private javax.swing.JMenuItem mniConsultarFornecedores;
    private javax.swing.JMenuItem mniNotas;
    private javax.swing.JLabel txtImagem;
    // End of variables declaration//GEN-END:variables
}
